/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _button_2player_selected_h_
#define _button_2player_selected_h_
//---------------------------------------------------------------------------------
extern const unsigned char button_2player_selected[];
extern const int button_2player_selected_size;
//---------------------------------------------------------------------------------
#endif //_button_2player_selected_h_
//---------------------------------------------------------------------------------
