/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _button_4player_h_
#define _button_4player_h_
//---------------------------------------------------------------------------------
extern const unsigned char button_4player[];
extern const int button_4player_size;
//---------------------------------------------------------------------------------
#endif //_button_4player_h_
//---------------------------------------------------------------------------------
