/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _button_1player_h_
#define _button_1player_h_
//---------------------------------------------------------------------------------
extern const unsigned char button_1player[];
extern const int button_1player_size;
//---------------------------------------------------------------------------------
#endif //_button_1player_h_
//---------------------------------------------------------------------------------
