/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _button_3player_h_
#define _button_3player_h_
//---------------------------------------------------------------------------------
extern const unsigned char button_3player[];
extern const int button_3player_size;
//---------------------------------------------------------------------------------
#endif //_button_3player_h_
//---------------------------------------------------------------------------------
