/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _button_2player_h_
#define _button_2player_h_
//---------------------------------------------------------------------------------
extern const unsigned char button_2player[];
extern const int button_2player_size;
//---------------------------------------------------------------------------------
#endif //_button_2player_h_
//---------------------------------------------------------------------------------
