/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _century_gothic_22_h_
#define _century_gothic_22_h_
//---------------------------------------------------------------------------------
extern const unsigned char century_gothic_22[];
extern const int century_gothic_22_size;
//---------------------------------------------------------------------------------
#endif //_century_gothic_22_h_
//---------------------------------------------------------------------------------
