/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _grrlib_logo_h_
#define _grrlib_logo_h_
//---------------------------------------------------------------------------------
extern const unsigned char grrlib_logo[];
extern const int grrlib_logo_size;
//---------------------------------------------------------------------------------
#endif //_grrlib_logo_h_
//---------------------------------------------------------------------------------
