/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _menu_background_h_
#define _menu_background_h_
//---------------------------------------------------------------------------------
extern const unsigned char menu_background[];
extern const int menu_background_size;
//---------------------------------------------------------------------------------
#endif //_menu_background_h_
//---------------------------------------------------------------------------------
